from enum import Enum

class ConversationState(str, Enum):
    START = "START"
    GREETING = "GREETING"
    INTENT_DETECTION = "INTENT_DETECTION"
    INFO_REQUIRED = "INFO_REQUIRED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    ACTION_IN_PROGRESS = "ACTION_IN_PROGRESS"
    WAITING_CUSTOMER = "WAITING_CUSTOMER"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"
    NO_RESPONSE_CLOSED = "NO_RESPONSE_CLOSED"
